version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "13:00"
    timezone: Canada/Eastern
  open-pull-requests-limit: 2
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  commit-message:
    prefix: chore
