# When in doubt, look up the CircleCI documentation, it has everything you need to know: https://circleci.com/docs/

version: 2.1

defaults: &defaults
  working_directory: ~/repo
  # Pick a Docker image here: https://circleci.com/docs/2.0/circleci-images/
  docker:
    - image: circleci/node:10.13.0

jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn lint
            - run: yarn test --coverage
            - run: bash <(curl -s https://codecov.io/bash)
            - run: yarn build

workflows:
    version: 2
    build:
        jobs:
            - build
